#!/bin/sh

# stop script at first fail
set -e

for file in "$@"
do
	echo "$file"
	name="`dirname $1`/`basename $file .vsl`"
	java -jar build/libs/TP2.jar < $name.vsl > $name.ll
	clang $name.ll -o $name.x
	exec $name.x > $name.out
	

	
done

